spring:
  datasource:
    url: jdbc:mysql://database-1.crpmmv1h0gln.us-east-1.rds.amazonaws.com/MoviesDB
    username: admin
    password: Guven12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
