version: '3.8'
services:
  db:
    image: mysql
    container_name: movie
    restart: always
    environment:
      MYSQL_DATABASE: 'movieDB'
      MYSQL_PASSWORD: 'guven12345'
      MYSQL_ROOT_PASSWORD: 'guven12345'
    ports:
      - '3306:3306'
    networks:
      - movieapi-network
    healthcheck:
      test: "/usr/bin/mysql --user=admin --password=guven12345 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  application:
    container_name: movieapi-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    networks:
      - blogapi-network
    depends_on:
      - "db"
networks:
  blogapi-network:
    name: movieapi-network
    driver: bridge
